cargo-features = ["profile-overrides"]

[workspace]
members = [
  "driver",
  "syntax",
  "physics",
  "db",
  "index",
  "query",
  "common",
  "tests",
]

[profile.dev.overrides."parser-macros"]
opt-level = 3

[profile.release]
panic = "abort"