[package]
name = "common"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
static_assertions = "0.3.3"
chrono = "0.4"
regex = "1"
hashbrown = { version = "0.5", features = ["nightly"] }
indexmap = "1.2.0"